Ontology development
BAMresearch/ModelCalibration pull request #20
Opened 2022-04-22 14:50 UTC by vandungdo

After a lot of tries, I finally fixed it (it worked perfectly when I run it locally with pydoit, but it showed an error on GitHub action and I don't know why @@). The reason is the rdflib version.

All steps in the workflow now (minimum working example workflow) went through, and are ready to be merged (I hope). It seems the test calibration workflow is not related to our work now, so I decided to delete it.

After merging, we can delete the ontology_development branch. And starting to create issues and branches...

2022-05-03 09:31 UTC, joergfunger requested changes
Not fully sure what is supposed to be adressed in this merge request, and what is supposed to be done afterwards.

2022-05-03 09:31 UTC, joergfunger commented on usecases/Concrete/dodo.py
> +        yield {
file_dep are missing

2022-05-03 09:31 UTC, joergfunger commented on usecases/Concrete/knowledgeGraph/emodul/emodul_metadata_extraction.py
> +def generate_metadata_yaml_file_from_emodul_BAM(locationOfRawData, locationOfMetaData):
I think the return function should rather be the dict, that you can then store in a separate file if needed (this way you can test the functionality without intermediate files in pytest)

2022-05-03 09:31 UTC, joergfunger commented on usecases/Concrete/knowledgeGraph/emodul/emodul_metadata_extraction.py
> +        'weight': column_data(metadata, operatorIndex, 'Bediener Information', 'Masse'),
if appropriate, assumptions on the units should be stored in the metadata dict as well

2022-05-03 09:31 UTC, joergfunger commented on usecases/Concrete/knowledgeGraph/emodul/emodul_test.py
> +print(input_emodul_data_for_calibration(nameOfExperiment)['processedDataPath'])
remove auxiliary prints

2022-05-03 09:31 UTC, joergfunger commented on usecases/Concrete/knowledgeGraph/emodul/emodul_validation.py
> +    conforms, result_graph, _ = validate(
why does validate return a result graph that is then further used? I would have expected that rdf_graph conforms, then the return value is true, or it does not, then it returns an error with the corresponding things that fail.

2022-05-03 09:31 UTC, joergfunger commented on usecases/Concrete/knowledgeGraph/mixture/extractMetadataFromMischung.py
> +for excelsheet in excelsheetlist:
Still not a function, this loop is done in pydoit by definining the dependencies e.g. [here](https://github.com/BAMresearch/ModelCalibration/blob/d60dd8e001e927050ab27907e7be282fe17b49fc/usecases/linearFunction/dodo.py#L29)

2022-05-03 09:31 UTC, joergfunger commented on usecases/Concrete/knowledgeGraph/shape.ttl
> +# for a documentation of shacl see https://www.w3.org/TR/shacl/
this is a specific shacle shape and should be named accordingly (not shape.ttl)

2022-05-13 12:00 UTC, joergfunger approved these changes

2022-05-25 14:20 UTC, joergfunger commented
@vandungdo What is the current status? Can we merge, or what would be a timeline?

2022-05-30 06:46 UTC, vandungdo commented
> @vandungdo What is the current status? Can we merge, or what would be a timeline?

The branch is now ready to be merged. Please ask @soudehMasoudian for adding her unit test script for each step in the new folder structure. Otherwise, we can merge it first and she needs to create new branch for testing

2022-05-30 06:46 UTC, merged